---
- include: _defaults.yml
  with_items:
  - desc: Accessibility / Disable reduce transparency in the menu bar and elsewhere.
    path: com.apple.universalaccess
    key: reduceTransparency
    value: -bool NO
    expect: 0
  - desc: Accessibility / Disable scroll gesture with the Ctrl (^) modifier key to zoom.
    path: com.apple.universalaccess
    key: closeViewScrollWheelToggle
    value: -bool NO
    expect: 0
  - desc: Accessibility / Disable Follow the keyboard focus while zoomed in.
    path: com.apple.universalaccess
    key: closeViewZoomFollowsFocus
    value: -bool NO
    expect: 0
