---
- include: _defaults.yml
  with_items:
  - desc: Use focus ring.
    path: NSGlobalDomain
    key: NSAutomaticFocusRingEnabled
    value: -bool YES
    expect: 1
  - desc: Use focus ring with animation.
    path: NSGlobalDomain
    key: NSUseAnimatedFocusRing
    value: -bool YES
    expect: 1
  - desc: Set 0.1sec when resize panel time span.
    path: NSGlobalDomain
    key: NSWindowResizeTime
    value: -float 0.1
    expect: 0.1
  - desc: Expand to default save panel. (1/2)
    path: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    value: -bool YES
    expect: 1
  - desc: Expand to default save panel. (2/2)
    path: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    value: -bool YES
    expect: 1
  - desc: Save to iCloud by default dest.
    path: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    value: -bool YES
    expect: 1
  - desc: Disable automatic termination of inactive apps.
    path: NSGlobalDomain
    key: NSDisableAutomaticTermination
    value: -bool YES
    expect: 1
  - desc: Enable show help on DevMode
    path: com.apple.helpviewer
    key: DevMode
    value: -bool YES
    expect: 1
