---
- name: Install office tools from mas.
  shell: 'mas install {{ item }}'
  register: mas
  changed_when: '"already installed" in mas.stdout'
  with_items:
  - 409183694 #Keynote
  - 409203825 #Numbers
  - 409201541 #Pages
  - 784801555 #Microsoft OneNote
  - 748212890 #Memory Cleaner
